sudo: false
language: python
python:
    - 2.7
    - pypy
    - 3.3
    - 3.4
    - 3.5
install:
    - pip install -U pip
    - pip install -U coverage coveralls
    - pip install .[test]
script:
    - coverage run setup.py test -q
after_success:
  - coveralls
notifications:
    email: false
